---
- hosts: all
  become: yes

  vars_files:
    - vars/main.yml

  handlers:
    - import_tasks: handlers/main.yml

  pre_tasks:
    - name: "Update system on Debian"
      apt:
        name: "*"
        state: latest
        update_cache: yes
      tags: "Update"

    - name: "Install required POSTGRESQL packages"
      apt:
        name:
          - postgresql
          - postgresql-contrib
          - python3-psycopg2
        state: present
        update_cache: yes
      tags: "PostgreSQL"

    - name: "Installer Apache et PHP"
      apt:
        name:
          - apache2
          - php
          - php-mbstring
          - php-xml
          - libapache2-mod-php
          - wget
        state: present
        update_cache: yes

    - name: Télécharger Adminer
      get_url:
        url: https://www.adminer.org/latest.php
        dest: /var/www/html/adminer.php
        mode: '0644'
      tags: "Adminer"

  tasks:

    - name: "Install and Start Apache on Debian"
      include_tasks: tasks/apache.yml
      tags: "Apache2"

    - name: "Check if PostgreSQL data directory exists"
      include_tasks: tasks/initpostgres.yml
      tags: "PostgreSQL"

    - name: "Create app database"
      include_tasks: tasks/createdb.yml
      tags: "PostgreSQL"

    - name: "Exécuter le script SQL"
      include_tasks: tasks/script.yml
      tags: "PostgreSQL"

    - name: "Allow md5 connection for the db user"
      include_tasks: tasks/pg_hba.yml
      tags: "PostgreSQL"
    
    - name: "Dump PostgreSQL database into a file"
      include_tasks: tasks/dumpSQL.yml
      tags: "DumpSQL"

    - name: "Configurer Apache"
      include_tasks: tasks/adminer.yml       
      tags: "Adminer" 
