- name: "Create app database"
  postgresql_db:
    state: present
    name: "{{ db_name }}"
  become: yes
  become_user: postgres
  tags: PostgreSQL

- name: "Create db user"
  postgresql_user:
    state: present
    name: "{{ db_user }}"
    password: "{{ db_password }}"
  become: yes
  become_user: postgres
  tags: PostgreSQL

- name: "Grant db user access to app db"
  postgresql_privs:
    type: database
    database: "{{ db_name }}"
    roles: "{{ db_user }}"
    grant_option: no
    privs: all
  become: yes
  become_user: postgres
  tags: PostgreSQL

- name: "Copier le script SQL sur la machine cible"
  copy:
    src: "database/sqldb.sql"
    dest: "/tmp/sqldb.sql"
    mode: '0644'
  tags: PostgreSQL
